import type { Metadata } from "next";

import { Noto_Sans, Noto_Sans_KR } from "next/font/google";
import Header from "./components/layout/Header";
import "@/lib/styles/global.css";
import Navigation from "./components/layout/Navigation";
import Content from "./components/layout/Content";
import Modal from "./components/layout/Modal";
import { CustomAlert } from "./components/common/CustomAlert";

const notoSans = Noto_Sans({
    subsets: ["latin"],
    weight: ["400", "500", "700"],
    variable: "--font-noto-sans",
});

// 한글용
const notoSansKR = Noto_Sans_KR({
    subsets: ["latin"],
    weight: ["400", "500", "700"],
    variable: "--font-noto-sans-kr",
});
export const metadata: Metadata = {
    title: "WSA 차량 관리",
    description: "Generated by create next app",
    icons: {
        icon: "/favicon.ico",
    },
    viewport: {
        width: "device-width",
        initialScale: 1,
        maximumScale: 5, // iOS에서 input focus 시 자동 확대 방지하면서도 사용자 확대는 허용
        userScalable: true,
        viewportFit: "cover", // Safari safe-area-inset 활성화
    },
};

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="en">
            <body
                className={`${notoSans.variable} ${notoSansKR.variable} antialiased`}
            >
                <CustomAlert />
                <Header />
                <Content>{children}</Content>
                <Modal />
            </body>
        </html>
    );
}
